### ISSUE TITLE
page reload

### ISSUE THREAD

**Issue by vijaychouhan-rails** [gunpowderlabs/greedo#4]
Its okay to reload the page if we are on the listing page.

but if we use greedo on a page where we have multiple listing for different purpose. in this case when click on the pagination link it will reload the whole page.

no matter we have more than one listing on a page, is this gem support to have Ajax call on pagination ?

**Comment by wrozka** [comment]
No, it doesn't support AJAX pagination. It is a very simple helper for generating tables.
